# Generated by Django 3.1.1 on 2020-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNUM', models.IntegerField(verbose_name='Номер покупателя')),
                ('CNAME', models.CharField(max_length=20, verbose_name='Имя покупателя')),
                ('CITY', models.CharField(max_length=20, verbose_name='Город проживания покупателя')),
                ('RATING', models.IntegerField(verbose_name='Некоторый рейтинг, присвоенный покупателю')),
                ('SNUM', models.IntegerField(verbose_name='Номер торгового агента, за которым закреплен покупатель')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ONUM', models.IntegerField(verbose_name='Номер заказа')),
                ('AMT', models.FloatField(verbose_name='Сумма заказа')),
                ('ODATE', models.DateField(verbose_name='Дата\xa0 заказа')),
                ('CNUM', models.IntegerField(verbose_name='Номер покупателя')),
                ('SNUM', models.IntegerField(verbose_name='Номер торгового агента')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Salespeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNUM', models.IntegerField(verbose_name='Номер агента')),
                ('SNAME', models.CharField(max_length=20, verbose_name='Имя агента')),
                ('CITY', models.CharField(max_length=20, verbose_name='Город, где работает агент')),
                ('COMM', models.FloatField(verbose_name='Коммисионные торгового агента')),
            ],
            options={
                'verbose_name': 'Торговый агент',
                'verbose_name_plural': 'Торговые агенты',
            },
        ),
    ]
